# Generated by Django 2.2.4 on 2020-04-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mybooksread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('thriller', 'thriller'), ('text_book', 'text book'), ('mystery', 'mystery'), ('classics', 'classics'), ('novel', 'novel')], default='novel', max_length=15)),
            ],
            options={
                'db_table': 'mybooksread',
                'ordering': ['-authors'],
            },
        ),
    ]
