# Generated by Django 3.0.6 on 2020-08-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooksread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
