# Generated by Django 3.0.6 on 2020-08-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_mybooksread_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooksread',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mybooksread',
            name='category',
            field=models.CharField(choices=[('thriller', 'thriller'), ('text_book', 'text book'), ('mystery', 'mystery'), ('classics', 'classics'), ('novel', 'novel'), ('sailing', 'sailing')], default='novel', max_length=15),
        ),
    ]
