# Generated by Django 3.0.6 on 2020-08-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200813_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooksread',
            name='image',
            field=models.ImageField(default=True, upload_to='collection'),
            preserve_default=False,
        ),
    ]
