# Generated by Django 3.0.6 on 2020-08-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200813_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooksread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collection'),
        ),
    ]
