# Generated by Django 4.1.7 on 2023-03-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200814_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooksread',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
